#!/bin/bash -e

echo "Post-Push hook running"

GIT_REV=$(git rev-parse --short HEAD)
# GIT_REV=${SOURCE_COMMIT:0:7}

docker tag "$IMAGE_NAME" "${DOCKER_REPO}:${GIT_REV}"
docker push "${DOCKER_REPO}:${GIT_REV}"
